apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secret
stringData:
    TUNNEL_ID: ENC[AES256_GCM,data:HmiUhtJc7aeHijpuqpo2Pk/ClZCPiidGaS0/2fmwNSr8sKtD,iv:mBwLyxcyE8IK2rxxv2S5Rw/AloJgMhqLPMQb9Gak9Tc=,tag:bcLGbaQIoxtko4hBVt69Eg==,type:str]
    credentials.json: ENC[AES256_GCM,data:sg6uVABpECvQvCT2cHKjHUlbtUPxeWWcGqF5megiEfQXa5nrZXVvo9tlNLyApU+6/PsJIcAz9+aq2OFOeuMf6GZEJE4Tg1+ujtVo1o9tqc8Cu5kNfD/ffAFL3ZF8F1+4WyZVEbvCpetDv7iDOLBLlLcrNVSRcJk6cN8ZCpwmFJwLSQhnGBbEvW/amwtqqeSbUgA+IFPWpp7EyEk5yJqjcwGpGOEsrRG7aUea0D4jhA==,iv:QIjF8B0GUTnvIxVo92xhrGVke+q8Hxw9WN0duVsgs48=,tag:xIB+Mhw9kahUM+fde687ZQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1hzt9ymapcvaksfm2k9h372lqrz43zdead4r80trjs7fj3jh2zvwqlz434f
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrNjEzU1JBeERCSzd0Wm1Z
            ci9UZ3NDRHUybjJtTFhGdU9teVd2NnN1ZTJrCkpjdWI4VDBJQ2FFYjRNQUxCQUxa
            NlV0YTQ0WHlJR0d1TndDT0tCV0xQV2sKLS0tIGJwSnhuSnIwRHpqdEE3Q05hclFR
            aUQ0eVo1SkdHelpaQmJLN25RNUpKemcKi02A1I5BBiU/5Ci8IqtsgD+vejJLfBlF
            Pl9ewm5BBmR70ZwPsGxsqqnCIRH2FFCHCU/ar8cnWVseZ4jedxHlGw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-07-04T21:21:32Z"
    mac: ENC[AES256_GCM,data:AWTcgisKee5qtq2C5ngigDl87yJq7bNpo9FZnQdm8lLl3BhRyFglGyF7Evz3ttWs22ueW1Gsy/qRJa3nUc4RKj4ZtmeI106rThK26cYjMTWJuNBB3vmNykpmepev208nluLRNn122yF+vAaSv5Ihsx7n2irXBpVQDFRfn4gofJ0=,iv:ZkL1qZwcHaFuF/+C9Q+TPbg3kCI697nrXIiuf99qwZU=,tag:WlCmuaOWmUuX2lQxxzH63g==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
