apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secret
stringData:
    TUNNEL_ID: ENC[AES256_GCM,data:D2DGs3z39j70/iujLsUHydVJObs9cmoeAST5rn4IyFOrwQLU,iv:GyiZz3KzXK+wwDr0AGhQiGjGBbs5dUrNTuT24ZjAJFk=,tag:KDyT/ySlHGZVkr9c3Gsegg==,type:str]
    credentials.json: ENC[AES256_GCM,data:aaHbPyNt/bs1bEt74+7KusiNFRucAQMJwETKKNn26HQSqD2L7RC1FyIBj/bRqmgILn2ioX3nQqa3iT253MtheSq6g81l5/yFKONx0O9ErCYE30VoIfUzXf8joQAKen9j3yg7ij9vQ28KzwJwv18klHUqfVzzhqAwxB9U0MUZQychkW/yD0WGUOTqGOTc6c8sKqYVhOGNdcgsJ03Lshac9d2Ifxh1XzfaCNShhBjZxQ==,iv:60VFQxMjDWixP4KEJGHhao/kA5cIVLckryfkurIBRXM=,tag:w86clqedRjaobAV6cZ+22A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1hzt9ymapcvaksfm2k9h372lqrz43zdead4r80trjs7fj3jh2zvwqlz434f
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2NUdweGp3VEtJT1hUSHR1
            akgxVXBYSTJtM2Fqc3V1R2R5bHc3NDVhWHg0Ck1IUXlWaUtJTkg5TlpEOVdhMGwy
            MDVsREdXN2ZJditsb2ZWT1lmbDIxV28KLS0tIFU3Z2VrcERNR21ZaFplRkFPaSsy
            bjU1cWVpV2pCVTZ5eTJvd1pteWtPSTQKJLtBdF9/buHXYj+n8NwqWafs2YZhV1rP
            8ooa9qfOahTaAXMpnOVifPMNzT66EdKyR2+b2+2KzFWVp0qcSbYveQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-07-01T00:44:17Z"
    mac: ENC[AES256_GCM,data:PhPZJBegkv6HKG7bDBUA3NVRDrdOop+ssmM/4qBO+1Yizt1HI1mxgdIBLkvsud2CeCIqgmy/Vqx5ME3qiZ91vMJ5nlQqIQM7L9ppQEhNmrpy+8WHbggYQ7NQVsJm/ZTJplMIUW/hwkdPl/5UmWGWaC7JDrx7KyLWnGbgRJnReFI=,iv:ib2jwC1Cwj4eE9wVsqcP1UCgL/RjAXRjeVDc+9mvmmQ=,tag:eumul9uQk0uEymxhg4KzKA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
