---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: twingate
  namespace: networking
spec:
  interval: 10m
  chart:
    spec:
      chart: connector
      version: 0.1.26
      sourceRef:
        kind: HelmRepository
        name: twingate
        namespace: flux-system
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    image:
      repository: twingate/connector
      tag: 1.69.0
    connector:
      logLevel: "info"
      network:
        secretKeyRef:
          name: twingate-secret
          key: TWINGATE_CONNECTOR_NETWORK
      url: "twingate.com"
      accessToken:
        secretKeyRef:
          name: twingate-secret
          key: TWINGATE_ACCESS_TOKEN
      refreshToken:
        secretKeyRef:
          name: twingate-secret
          key: TWINGATE_REFRESH_TOKEN
      dnsServer:
        secretKeyRef:
          name: twingate-secret
          key: TWINGATE_DNS_SERVERS
