---
# yaml-language-server: $schema=https://kube-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app unifi-dns-webhook-3226
spec:
  interval: 30m
  chart:
    spec:
      chart: external-dns
      version: 1.15.0
      sourceRef:
        kind: HelmRepository
        name: external-dns
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    fullnameOverride: *app
  #  logLevel: debug
    provider:
      name: webhook
      webhook:
        image:
          repository: ghcr.io/kashalls/external-dns-unifi-webhook
          tag: v0.2.2@sha256:7778b1e932e920181007be34bb03306722e85fc8ded34cd87c0f16060b9f07e3
        env:
          - name: UNIFI_HOST
            value: https://10.32.26.1
          - name: UNIFI_USER
            valueFrom:
              secretKeyRef:
                name: &secret unifi-dns-webhook-3226-secret
                key: EXTERNAL_DNS_UNIFI_USER
          - name: UNIFI_PASS
            valueFrom:
              secretKeyRef:
                name: *secret
                key: EXTERNAL_DNS_UNIFI_PASS
          - name: UNIFI_SKIP_TLS_VERIFY
            value: true
        #  - name: LOG_LEVEL
        #    value: "debug"
        livenessProbe:
          httpGet:
            path: /healthz
            port: http-wh-metrics
          initialDelaySeconds: 10
          timeoutSeconds: 5
        readinessProbe:
          httpGet:
            path: /readyz
            port: http-wh-metrics
          initialDelaySeconds: 10
          timeoutSeconds: 5
    extraArgs:
      - --ignore-ingress-tls-spec
    policy: sync
    sources: ["ingress", "service"]
    txtOwnerId: main
    txtPrefix: k8s.main.
    domainFilters: ["${SECRET_DOMAIN}"]
    serviceMonitor:
      enabled: true
    podAnnotations:
      secret.reloader.stakater.com/reload: *secret
