apiVersion: v1
kind: Secret
metadata:
    name: cluster-user-auth
stringData:
    password: ENC[AES256_GCM,data:0D8AtookU82mcQW9j/z5FspsZT4nfh4=,iv:SWch45NeTF7zr1AyXuNitg4hGE9DnDJ3t6y1GQ0xiFI=,tag:p/eiaGy4u4lnXK20Mj/awA==,type:str]
    username: ENC[AES256_GCM,data:ycj2J43pVcQl+TvX4RsKUGrdI+lZ13v2XSA=,iv:xNIA7NHliyOllLoMb/jbl1lOSB6R5s+LX5VG5Ceynak=,tag:rl2A1pvmbzOIlOTauZkAlA==,type:str]
type: Opaque
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1hzt9ymapcvaksfm2k9h372lqrz43zdead4r80trjs7fj3jh2zvwqlz434f
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDTXJDWVY5d2NtV2liVm5s
            L1VCNTRpaWo4MUpGVmtOQ21LZ0pLL2V1YjFvCnBOMUJMcE9SZWdseEh0OWR3VmhY
            S3BmOVRJWU5SL3FvU0QxWjlqRkpvVUkKLS0tIFFJcEIwOU0xdXgyMHFGeExEQmgz
            Mi81UzBKSXEzbWJDaWNjUGhHZEpyUGsK5sk2Qkz7pbZGOPcT9kLyt/aretKY+Xde
            01/nhCp+pg5Z7IO+ubbd6CbG805ghNIGv+zPtQ6mlUiHOdKw48VYQQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-07-18T19:53:04Z"
    mac: ENC[AES256_GCM,data:SQ+ny7AnUgjocGjvejf8qqAEw4SuwvHI99WTnvDZhsvYNiIcYfXR5FBr4fpBzV5Ch5soErapkdhWP12qrYYlQvoWjoJWgtCESHtWESZV5uV/RSKmrxXFBayUwSlmOP0ValSzJsrLsj9bU42vs44fDVPoabwhdHp911NKsjuc2pM=,iv:za4eM97sEBXTLhn+BAzT/BNU4MsJcBWZKYw9kAmwKJU=,tag:TReQGNbhoGoNM/3ebdoAHQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
