kind: Secret
apiVersion: v1
type: Opaque
metadata:
    name: unifi-dns-webhook-3226-secret
    namespace: network
stringData:
    EXTERNAL_DNS_UNIFI_USER: ENC[AES256_GCM,data:wZvvBi4tHRjUD6Xntj1uTvJ+7A==,iv:kKeWSN1xG+d6e2AgYYNMEXfhn+GQLlDou/RrsMsfc1w=,tag:+StfUfy6nBwjjJlzDigMAA==,type:str]
    EXTERNAL_DNS_UNIFI_PASS: ENC[AES256_GCM,data:yoRRwgQUpzYm0U8bB49O8S8e/Gdj5n7/B74VhK9PirVOSA==,iv:qr9ygCFslfSn0M2aHP4DEIeohHLPnyLNKsxJrc2Jee4=,tag:lx0vVgESH4y2c4dgksrzSw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1hzt9ymapcvaksfm2k9h372lqrz43zdead4r80trjs7fj3jh2zvwqlz434f
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnSE1KSmZPNUlsTTY5UUht
            U2Y2UDZtWU8wK3FNNDByQks4YlBUNEJFVzJNCjdVNnpKOHVPd2JzMEhXdHVuT0JQ
            alF2NGFKSkJHdllsaDhJSmppNE5HOVUKLS0tIElCemh1NStQcmtybzZ2NUpsK2NY
            ZDFLa2pmVGVqN3JIMmFzbDE1RzBkYTQKz5876H5rDweIL6d4BJ+llDwq6qGvWUYA
            D3e9WGcoEBsI7qhpXby84sMvBMa2kcLjczErahiielGDi23c52/fQQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-21T23:44:28Z"
    mac: ENC[AES256_GCM,data:FXxY9tQTd+FyWd+zF84u32rUq8p4sbVRsC+svdfpothJ/8GliJh6LOu9Z5R3xG6yjmkbnOhbI/kv0GUSQjhw12C8aMBlyHyNOGIKdG2rL7MjwEu83ZzELI3+vbjALiSrR5tOJqPepmedYMsrS/bslHODWXY3xhNRxOdy7+ruNQ0=,iv:3xe/zqknlB9OvwafIJOAXtu4FRefMgmLLJNin1U2dag=,tag:jhGbyanwhYG79cQpZdlsjg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
