apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:XMiK5I/lRda3oI+/Xg==,iv:H9y9w0gmIgy5srffRn9W87G6THBwYSKKM4pT67LvwaI=,tag:ulMja+aQbHzijl+7cXKgfQ==,type:str]
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:1tseqbslqOO+/TBa0ePn,iv:rlUGQcWbKQNgTBW4MChLRz3cr37OdubYORy9WMzYWbw=,tag:viJqavF8ZQVAnkCoEquI6Q==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:149qgtJOx08YTpCsI0OMLmO2otcuxRosmcyj4VXPQq1Q9FSH,iv:Yi20jT2YS7yf2YK7eOxjc1fZDlXgsSvxURLQWjBFGMU=,tag:OLokGTpve4R9O+l+woiGAA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1hzt9ymapcvaksfm2k9h372lqrz43zdead4r80trjs7fj3jh2zvwqlz434f
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvekR2d0VobzU2bHUydFV5
            M1Q2UVZGRXpaL0l0ZkZuRXE3RG1JRWs0TEZzCldUWFBaWlplYVlaUmNmZDJWOU4r
            NkZpM24xNWg2TEI2KzIwbjl3ZlFMWTAKLS0tIFNkcTd2QVJyTURqOTBQZmNRMDFF
            d1UyNE9ranY1YWtoU2Zza1NsUEg0Tk0KcyBiJur3sQ0St6zhJK5k/67uzbckEV1v
            zQpFC52pzcqj3u36TBlmler2CsP3cMYDJ40fgIdeDJpS5tiYokOEkg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-07-04T21:32:17Z"
    mac: ENC[AES256_GCM,data:HkB5zxQfSWq/fAD7Q7pVlyRWK53W8NEElk/AD+ZFc11quG9GdNFwB/cqdikcRCDO55p4BM2lA6EJAyJNGlbAHwxDSoPBfaCkgiec/N9A42POUQIPfbCg3E4fcq1gVVZ1N9hjKpIUFSj9zqRbiWZeQp7XzVQGDexicz2j8/hp7dg=,iv:z5+FjPrA9NKe0+ArEb+X2IXKzMkG2pfLsC75PzPy8cI=,tag:GyyF33PweErlWISIun7dlg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
