apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
stringData:
    token: ENC[AES256_GCM,data:TN6XNTuNBUDm70YY+D+Wmm7+8k9ntb6d9n7T/k17llE=,iv:NWyv9gll6wH6lV3qi0AJhFVn29InUKHoWbcvpPu343A=,tag:aTJc8Ybq2BxxGaJqGO8a/A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1hzt9ymapcvaksfm2k9h372lqrz43zdead4r80trjs7fj3jh2zvwqlz434f
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBndlFMdDY5MEdBc1d4OWcz
            WDZZd2EySDdpeVZsYnBDdTRBSXdKZVIrK1hJClUzTnhPM2dvSWpsREVyclQxOVV2
            VXI0V1o0dEhDaEEvbTJtMDJROXpZQVEKLS0tIElrUjZaaUJ5MXNYeThFanNUWExN
            MGN2UlVLWVhyR1NhVFJTTXVqT0ZxK1EK2IsUVTzvowMavc5yjGaUWzpdblLzKPXW
            vmbhhuphywGH7lrHYrfnEhHgUtVZuRdyp7hBZwCcPX5opZAY6ZHktg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-07-01T00:44:17Z"
    mac: ENC[AES256_GCM,data:ASRNco/Wyl35NacE0TjooFBHsRXpcAgwo/JyDfIvbRUJZ13ib1O+F0aJqVBldukAFxchzxizr40cWAzlkT9s9XZXbWk/4iFIM8/QVLsRgzkwVolAy1zGTOrzV21uruZJS5nfWWJKhdj5iFfkXyUU4xbRvoeHHLvvlIouFm2NHgA=,iv:BIRR+zyiD63Eynr9CGVnz73IFAEjLLKwype3kTfrv2Q=,tag:tUlNZ3fJzGLFrubG1N0qww==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
