apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
stringData:
    api-token: ENC[AES256_GCM,data:ZItRJG65Mb8x/E6CDVtxhmxpDEYXAqMilc4q2nEOw+YK0vegfMnTnw==,iv:MUymdSU6ufcEq5RrqUarrr0UIMNHEXFxyZEuEE2BnQQ=,tag:m0/1xHjSagxyV67qVDACUA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1hzt9ymapcvaksfm2k9h372lqrz43zdead4r80trjs7fj3jh2zvwqlz434f
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTUEMyeTZHVjRkVXFOVmRQ
            YWMzNFRzNE4wNnBUcXFlYjhvRmVwNFovWFJnCmsxODIzNEptRTVVbnNaRGdWcG5a
            MmFHbzRweHRtSXNTNS9HY0tkRUljQm8KLS0tIHlJRitNZnArR0U2RVl4Uk0vTmh0
            NFVWQmFlWWVOL215M1EwV2E0d05LYW8Kzz0oriZO9z+5yVBdh84tQPFg1qZR7fbz
            M1OSQrFm1PulhajGAERm8/jdGOYvZyOdFWdSDtULZ2YfoGKzDb4bWw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-07-01T00:44:17Z"
    mac: ENC[AES256_GCM,data:g2q+vgKtWSFewQfkzjmocKm2qamVybsyomPQKLllkM93+ZxK4W2uFaS6KHc8s663NauPt13zgAmYESPYOZXSgS9U29UF8DqTwwQra3E1nCHyxN4s+GYsuapWQAsaPzUAwsCAwXvn50ZZj0HemFNPzUC4we2xHXX4zZzSTBqLJJk=,iv:lN2gjOZ1U5VkHPQX73BSY7dcnxj50Wfsr4iXQMJlXjc=,tag:zT2WOqqV28q92ZAJJ6dUQw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
